hc/front/tests/test_basics.py, hc/front/views.py
if the temporary code ever disappears, you don't want the user to get stuck on the welcome screen
with tests
=> make welcome code logic resilient

hc/accounts/tests/test_check_token.py, hc/accounts/views.py, hc/front/views.py
If the user is already logged in, and then click the login email again, they get hit with this:
The reason is that their login token has been reset already, but they do have a valid session at the moment.
Correct behavior is to redirect the user to the checks screen instead.
and a small perf change that I saw while reading through the code
=> redirect already logged in user

hc/accounts/tests/test_check_token.py, hc/accounts/tests/test_login.py, hc/accounts/views.py
Try going to this URL:
https://healthchecks.io/accounts/check_token/invalid_user/invalid_token/
You'll get hit with the login page, and u can enter email all day long and it wouldn't work
Correct solution is to:
- upon bad token or bad user, redirect over to login page
- set a `bad_link` sentinel in the cookie for the login page to render the special invalid login message
- clear the `bad_link` sentinel from session
with unit tests included
=> check token need to handle invalid user & invalid token correctly

hc/front/views.py
welcome check may be expired now, docs page will crash in that case
fix it by re-using the same welcome check logic from index page
=> fix docs page crashing if welcome code is expired

.travis.yml
I noticed that in coverall, the test files were counting towards code coverage
tests should be excluded from coverage information
=> dont include tests in coverage calculation

static/js/login.js
the password input field is hidden in the DOM, but that still means password managers will pick it up and insert into a password to use
if I have a password manager with multiple accounts + passwords, this can screw up the login experience
if the password input field is ONLY inserted into the DOM after the toggle has been checked, then the password managers will not be tricked.
I know this is an edge case with how browser password managers work, but the way I fixed it doesn't cause any interaction flow to existing users.
=> defer inserting the password field into the dom

hc/front/tests/test_remove_channel.py, hc/front/views.py
removing the channel may be a slow operation and if the user refresh in the middle of the request, Chrome will make a 2nd POST request, which will end up erroring
I think it's better to always redirect the user to the channel list regardless of whether the removal UUID was valid or not, better than showing an error page if the user sends two removals simultaneously
=> remove channel should always redirect even if removal fails

hc/api/models.py, hc/api/tests/test_notify.py
Adding "healthcheck.io" as User-Agent to inform webhook handler server about request is specific from healthcheck.
=> Add healthcheck UA to inform server about identity

hc/api/tests/test_ping.py, hc/api/urls.py, hc/api/views.py
when an incoming http request comes through a proxy, it will get the header `HTTP_X_FORWARDED_FOR` and `HTTP_X_FORWARDED_PROTO`
see protocol information https://en.wikipedia.org/wiki/X-Forwarded-For
The `ping` API should also hard enforce that its response not be cached so that any proxy in between don't screw it up.
=> forwarded for and forwarded protocol

README.md
SSH based cloning of the healthchecks repo doesn't work for users who do not have their keys added, resulting in a `Permission denied (publickey)` error. However, HTTPS cloning does work as expected.
=> Proposed change from SSH to HTTPS in installation instructions.

hc/settings.py
Using new backend name which come with Django 1.9 django.db.backends.postgresql instead of django.db.backends.postgresql_psycopg2
=> Using backend name django.db.backends.postgresql

hc/api/tests/test_list_checks.py, hc/api/views.py, templates/front/docs_api.html
Another sort-of-rough-draft pull request for allowing an API client to obtain a list of existing checks.  It's missing the list of channels and probably some bullet-proofing.
=> Implement GET /api/v1/checks/ for listing existing checks

hc/front/management/commands/pygmentize.py, static/css/docs.css, static/css/my_checks.css, static/css/snippet-copy.css, static/css/welcome.css, static/js/snippet-copy.js, templates/base.html, templates/front/docs.html, templates/front/docs_api.html, templates/front/my_checks.html, templates/front/snippets/bash_curl.html, templates/front/snippets/bash_curl.txt, templates/front/snippets/bash_wget.html, templates/front/snippets/bash_wget.txt, templates/front/snippets/create_check_request.txt, templates/front/snippets/create_check_request_a.html, templates/front/snippets/create_check_request_a.txt, templates/front/snippets/create_check_request_b.html, templates/front/snippets/create_check_request_b.txt, templates/front/snippets/python.html, templates/front/snippets/python.txt, templates/front/snippets/python_requests.html, templates/front/snippets/python_requests.txt, templates/front/snippets/python_urllib2.html, templates/front/snippets/python_urllib2.txt, templates/front/welcome.html
Adds copy-to-clipboard links to code snippets in the following places:
- the welcome page for not-logged-in users
- documentation
- My Checks → gear icon → Usage Examples
I'm using clipboard.js, and I'm setting the target text dynamically by parsing the corresponding pygments `.highlight` element, and ignoring all text within pygments's comment classes. This allows the snippet text files to have as many comments as we want while ensuring that they're never copied to the clipboard along with the actual code.
Implements #88
=> Adds 'copy to clipboard' function to example code snippets

hc/api/management/commands/sendalerts.py
Allow`sendalerts` to be run by an external scheduler, on a one-shot basis, exiting after all alerts have been sent.
=> Add --no-loop option to sendalerts management command.

hc/api/models.py
`datetime.isoformat` returns different date formats whether microseconds part equals 0 or not.
> __datetime.isoformat([sep])__
> Return a string representing the date and time in ISO 8601 format, YYYY-MM-DDTHH:MM:SS.mmmmmm or, if microsecond is 0, YYYY-MM-DDTHH:MM:SS
ref: https://docs.python.org/2/library/datetime.html#datetime.datetime.isoformat
`datetime.isoformat` function is used in the API and thus producing inconsistency in the API.
[Tests assume the microseconds equals 0](https://github.com/healthchecks/healthchecks/blob/20b046cba717790aa1f55de4a60a83eedafa57ce/hc/api/tests/test_list_checks.py#L15) so let's skip microseconds part from the API as well
=> Return consistent date formats in API

hc/api/models.py, hc/api/tests/test_notify.py, hc/api/transports.py, hc/front/forms.py, hc/front/tests/test_add_webhook.py, hc/front/views.py, static/js/webhook.js, templates/front/channels.html, templates/front/log.html, templates/integrations/add_webhook.html
Adding Content-Type header to Webhook integrations to work correctly with services like [IFTTT Maker Webhooks](https://ifttt.com/maker_webhooks) which require a specific content type, like application/json.
If the content-type is not provided, the post data is not parsed by IFTTT, which prevents the ability to use variables like, `$NAME` and `$STATUS`
=> Adding Content-Type header to Webhook integrations

templates/front/my_checks.html
I wanted to check the cron cheatsheet and got annoyed because it opened on the same tab, so I had to go back and open the window/modal to edit the cron period, and open the cheatsheet again, but this time on a new tab, so I could build my cron expression side-by-side.
=> Minor HTML edit on my_checks.html

hc/settings.py
When running the migration command from outside of the application directory the sqlite database is created in the current working directory at the time of the command being executed. This commit updates the file path to be relative to the location of the settings file.
=> Added deterministic handling of sqlite database location

templates/front/docs_api.html
Based on this change: https://github.com/healthchecks/healthchecks/commit/166115ebfbcffd68ce7f6d2494657fff0e70575d
=> Update docs to reflect new maximum timeout value

hc/accounts/models.py
urlsafe_b64encode return a byte, which will result in an api key saved with something like b'apikey'
I did not tested it but [urlsafe_b64decode](https://docs.python.org/3/library/base64.html#base64.urlsafe_b64decode) looks like doing the job also.
=> Setting api key will save it as a byte

hc/api/management/commands/smtpd.py
smtpd doesn't work with python3.6
Note, I haven't tested this with python 3.5 yet. Let me know if you're interested in merging and I will test.
=> Fix for Python 3.6

README.md
pip install will fail when you cannot compile some of the dependencies.
one is gcc the other is the Python.h
```
Building wheels for collected packages: rcssmin, rjsmin
Running setup.py bdist_wheel for rcssmin ... error
Complete output from command /home/ubuntu/webapps/hc-venv/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-ipfho29k/rcssmin/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-u0q6mggl --python-tag cp36:
running bdist_wheel
running build
running build_py
creating build
creating build/lib.linux-x86_64-3.6
copying ./rcssmin.py -> build/lib.linux-x86_64-3.6
running build_ext
building '_rcssmin' extension
creating …
```
=> update Readme with pip install dependencies

requirements.txt
```
Collecting croniter==0.3.26 (from -r requirements.txt (line 1))
Could not find a version that satisfies the requirement croniter==0.3.26 (from -r requirements.txt (line 1)) (from versions: 0.1.4.macosx-10.5-i386, 0.1.1, 0.1.2, 0.1.3, 0.1.4, 0.1.5, 0.1.6, 0.2.0, 0.2.2, 0.2.4, 0.2.5, 0.2.7, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5, 0.3.6, 0.3.7, 0.3.8, 0.3.9, 0.3.10, 0.3.11, 0.3.12, 0.3.13, 0.3.14, 0.3.15, 0.3.16, 0.3.17, 0.3.18, 0.3.19, 0.3.20, 0.3.22, 0.3.23, 0.3.24, 0.3.25, 0.3.28, 0.3.29)
No matching distribution found for croniter==0.3.26 (from -r requirements.txt (line 1))
```
croniter 0.3.26 has been deleted since croniter had a history stripping.
please refer to https://pypi.org/project/croniter/#id1
- Update croniter to 0.3.29
=> Update croniter to 0.3.29

README.md
Today I run into the problem that I needed to run db migration and I found nothing in the readme about this. So I wanted to add it that everyone can find it.
=> Add hint to run db migration in production

hc/front/forms.py
The existing 40 character limit prevents using the integration will Matrix servers that might have a fairly lengthy hostname (ie. 'matrix.internal.example.com' would only allow 12 characters for the
room name or ID, and room IDs are 19 characters long).
Increasing the `max_length` to `100` is still fairly arbitrary but itdoes match up with the `max_length` of the `name` field of the `Channel` model and should cover most instances.
=> Increase allowable length of Matrix room alias

templates/docs/attaching_logs.html, templates/docs/attaching_logs.md, templates/docs/bash.html, templates/docs/bash.md
Passing `--data-raw` to curl implies the request is method will be POST.
Unless we intend to do something entirely different, -X method override
shouldn't be used.
Curl's author Daniel Stenberg (@bagder) wrote about this back in 2015
https://daniel.haxx.se/blog/2015/09/11/unnecessary-use-of-curl-x/
=> Remove redundant '-X POST' to curl

templates/docs/resources.html, templates/docs/resources.md
From its README:
Why Do I Need This Instead of Calling curl from a Shell Script?
In addition to clean separation of concerns from the thing that needs to
run and the act of calling an external monitor, runitor packs a few neat
extra features that are bit more involved than single line additions to
a script.
It can capture the stdout and stderr of the command to send it along
with execution reports, a.k.a. pings. When you respond to an alert you
can quickly start investigating the issue with the relevant context
already available.
It can be used as a long running process acting as a task scheduler,
executing the command at specified intervals. This feature comes in
handy when you don't readily have access to a job scheduler like crond
or systemd.timer. Works well in one process per …
=> Add runitor to resources.{md,html}

templates/docs/monitoring_cron_jobs.html, templates/docs/monitoring_cron_jobs.md, templates/front/snippets/crontab.html, templates/front/snippets/crontab.txt
- That way the user could still receive logs e.g. by using the traditional `MAILTO` attribute of cron.
- Maybe the system would deliver the outputs over the default notification-system - the usage of the pipe operator breaks this for every command in the chain.
=> Switched from pipeing to --output /dev/null for curl

README.md, hc/accounts/backends.py, hc/accounts/middleware.py, hc/accounts/tests/test_remote_user_header_login.py, hc/settings.py
I wanted to self-host healthchecks and integrate it with my central authentication system (see #185), so rather than develop something specific to my needs, I added support for HTTP header-based authentication. This way, people can integrate whatever auth system they want (LDAP, mTLS, SAML, OAuth, whatever) at the reverse proxy level and remove the need for healthchecks to care about the implementation details.
I added two new settings (with corresponding environment variables):
1. `REMOTE_USER_HEADER` &mdash; set this to the header you wish to authenticate with. HTTP headers will be prefixed with `HTTP_` and have any dashes converted to underscores. Headers without that prefix can be set by the WSGI server itself only, which is more secure.
2. `REMOTE_USER_HEADER_TYPE` &mdash; If set to …
=> Add http header auth

templates/docs/python.html, templates/docs/python.md
There is a small typo in templates/docs/python.md.
Should read `library` rather than `libary`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
=> docs: fix simple typo, libary -> library

README.md
I wanted to play with customizing the source for my use but had to manually install `libpq-dev` on my Ubuntu 20.04 install and `wheel` in my venv, so I'm adding those steps to the README to make it easier for others.
=> Update README.txt to include more dev setup steps

templates/integrations/telegram_message.html
so you can see whether it's up or down at first glance
=> Add colored emojis to telegram messages

static/css/ping_details.css
The line height in the ping request body is being set by the bootstrap.css body tag to 1.42857143. The additional line height makes request bodies with unicode characters have spacing between lines that shouldn't be there.
Before:
After:
=> fix line height on request body

templates/emails/alert-body-html.html
Not all email clients are formatting the `ping.body` contents uniformly. Even using different applications from the same email provider results in a different display of the `ping.body` contents. There are two basic issues:
* Not all email clients are honoring the fixed-width font that should be used inside `<pre>` tags. Using fixed-width font is listed in the definition on https://www.w3schools.com/tags/tag_pre.asp
* Not all email clients are displaying the text with a 1em line height. This was a recent change to the healthchecks WebUI in 9fd9c8e4efd0c87c015215ae56eada88a7d07b6b but is not part of the definition of the `<pre>` tag. I'd like to add this to the emails to make Healthchecks more uniform between the website and the email notification.
Gmail Webmail:
Gmail Android App: …
=> Added formatting on ping.body in emails

docker/Dockerfile
Build on my raspberry pi 4 (`armhf`) was failing due to the cryptography python package trying to build Rust dependency. Find below a snippet taken from the build logs:
```
running build_rust
=============================DEBUG ASSISTANCE=============================
If you are seeing a compilation error please try the following steps to
successfully install cryptography:
1) Upgrade to the latest pip and try again. This will fix errors for most
users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
2) Read https://cryptography.io/en/latest/installation.html for specific
instructions for your platform.
3) Check our frequently asked questions for more information:
https://cryptography.io/en/latest/faq.html
4) Ensure you have a recent Rust toolchain installed: …
```
=> [DOCKER] Fix failing docker build on arm due to cryptography trying to build rust

.github/workflows/publish_docker_image.yml
Hi, this PR add the CI jobs required to build and push the docker image at each release.
We should add two repository secrets:
- DOCKER_USERNAME
- DOCKER_PASSWORD
Thanks
=> Publish docker image on release

hc/accounts/forms.py, hc/accounts/migrations/0043_add_role_manager.py, hc/accounts/models.py, hc/accounts/tests/test_project.py, hc/accounts/views.py, hc/test.py, templates/accounts/project.html
This PR adds a manager permission as mentioned in the related issue.
The boolean field `Member.rw` is migrated to the enum field `Member.permission`.
Managers are allowed to invite/remove team members except themselves.
Closes #484
=> feat: manager role

docker/docker-compose.yml
Use data folder otherwise a second volume is created that becomes orphaned after a docker-compose down.
That means that, currently, after each up&down you start with a fresh database.
=> Fix db-data volume in docker-compose.yml

docker/Dockerfile
This massively reduces the size of the container, by removing things which aren't needed, and not downloading them in the first place.
Required a special case for `psycopg2`, as `libpq-dev` isn't included in debian slim.
`python:3.9`: 332mb compressed, 911mb uncompressed.
`python:3.9-slim`: 43mb compressed, 122mb uncompressed.
Quite a saving by doing almost nothing.
=> Use slim version of the container

hc/front/views.py
This is simple fix adds another metric to prometheus endpoint - `hc_check_in_progress`. Its purpose is to return `1` for checks which are currently in progress (marked as `started`, and not finished or failed). 
The main purpose are prometheus alerts. For example, in my case some of the cron tasks use 100% CPU, and it's normal - which means, I don't want to receive alerts from prometheus/alertmanager about CPU usage during this time. Thanks to this simple metric, I can add simple rule like `node_load5 > 8 and on() hc_check_in_progress{name="my-heavy-cron-job"} == 0` and never be bothered unnecessarily again :)
=> Add `hc_check_started` prometheus metrics

hc/api/management/commands/smtpd.py
Found a particular scenario where the software (Veeam Agent) sending the email notifications that also have to be processed as pings, allows to send to one fixed recipient address only.
If I forward these emails, from that address to the multiple checks/recipients that I need (filtering via subject in Healthchecks), it sends them in one connection using multiple RCPT TOs, and Healthchecks just processes the first one.
This little change allows it to process multiple RCPT addresses and may be useful for this particular case and others.
=> Add support for multiple RCPT TO in incoming email

README.md, hc/local_settings.py.example, hc/settings.py, templates/docs/self_hosted_configuration.md
I've added `EMAIL_USE_SSL` to the environment variables handled by `settings.py` and changed the default SMTP port to `465` which is the recommended one over `587`. I've also set their default value to `False` as they can't be both `True` at the same time. A user who wants to use either one has to specify the correct one.
I've also updated the `README.md` with the new configuration setup.
=> Add support for SMTP with implicit TLS

hc/api/models.py
In an Azure deployment, there were issues saving ping objects to the database because the addresses appear to come in with ports attached to them (123.123.123.123:5314), which breaks the [GenericIPAddressField](https://docs.djangoproject.com/en/4.1/ref/forms/fields/#genericipaddressfield) constraint on the [Ping model](https://github.com/healthchecks/healthchecks/blob/11997e75c8b82981537234f236e0abb878afeeee/hc/api/models.py#L497). This had the following results: 
- Pings not actually saving to the database
- Hitting ping endpoints would result in 500 status codes
- Check's status would change, but no logs would appear on the page
I was able to make this change locally and push a container based on it into Azure and the fix works.
=> Remove port portion of remote_addr to fix Azure deployments

hc/api/tests/test_notify_slack.py, hc/api/transports.py, templates/integrations/slack_message.json
We were missing the body / payload of the last request triggering a notification. 
Hence we added the body to the template, if it exists.
=> Add body to Slack Notification

README.md, hc/front/views.py, templates/front/ping_details.html
I believe the title says it all.
=> For email pings, "ping details" dialog box should default to show html if exists, otherwise to plain text.

hc/api/tests/test_notify_msteams.py, hc/api/transports.py, templates/integrations/msteams_message.json
Support it like it does in https://github.com/healthchecks/healthchecks/blob/master/templates/integrations/slack_message.json The markdown codeblock works well in teams also.
=> Include body in msteams template if exists.

hc/api/management/commands/smtpd.py
Prior to 4b05fc6a8c5687640d30138a48a1403cc54898f4, the smtp daemon was working nicely as a daemon, i.e. without stdin attached (common in service scenarios like systemd). Since that commit, the daemon now relies on stdin being available and actually returning something that is **not** EOF, so you can't attach it to `/dev/null` or similar. You must have a full terminal available to run that as a daemon, which is not what a daemon usually is 😄 
This change removes the dependency on stdin and instead falls back on a more traditional SIGINT behaviour: Run until a SIGINT/CTRL-C is received, then exit.
=> Fix smtpd service without stdin

docker/Dockerfile
More suitable and less error prone to use in scripts.
https://manpages.debian.org/buster/apt/apt.8#SCRIPT_USAGE_AND_DIFFERENCES_FROM_OTHER_APT_TOOLS
=> Switch to apt-get

templates/docs/email.html-fragment, templates/docs/email.md, templates/front/filtering_rules_modal.html
We should specify that the keywords are case sensitive - this isn't obvious to the user. I determined this based on my own testing.
=> Update filtering rules to specify that they are case sensitive

hc/api/apps.py, hc/api/transports.py
Added  warning message if APPRISE_ENABLED is set to 'True' in settings, and python package 'apprise' is not installed.
Before changes APPRISE_ENABLED was being set to false without warning when apprise was not installed, even if it is enabled in settings.py
Fixes: #1020
=> Show warning if apprise is enabled but apprise package is not installed

hc/front/forms.py, hc/front/tests/test_add_trello.py
When creating Trello integration I got 400 after selecting the board to put notifications into.
It turns out the token I got from Trello does not match the regular expression as it has the following format:
"ATTA" + 64 hex chars (lowercase) + 8 hex chars (uppercase)
That "ATTA" prefix does not match `^[0-9a-fA-F]{64,256}$`. Just in case I changed the range from `a-fA-F` to `a-zA-Z` and added `_` and `-` (all base64 url-safe characters).
=> Fix Trello integration (token regexp too specific)

hc/api/apps.py
The version check implemented was wrong for e.g. version "11.3".
This commit makes the version check more robust.
=> Fix MariaDB version check in mariadb_uuid_check()

docker/uwsgi.ini
When only a port is specified, uWSGI will only listen on the IPv4 wildcard (0.0.0.0) address. This will break environments relying on IPv6.
Use `http-socket = [::]:8000` to have uWSGI listen on IPv4 as well as IPv6.
=> docker: default to listening on IPv6 as well

hc/accounts/management/commands/createsuperuser.py, templates/docs/self_hosted.md, templates/docs/self_hosted_docker.md
Useful where multiple instances are deployed via CI/CD pipelines, superuser credentials can be passed down from pipeline secrets, automatically creating the superuser after deployment. Removes one more manual configuration step.
It would go something like this for docker-based deployments: 
```
docker-compose run -e SUPERUSER_EMAIL=test@mail.com -e SUPERUSER_PASSWORD=test123 web /opt/healthchecks/manage.py createsuperuser
````
or for local/development:
```
SUPERUSER_EMAIL=test@mail.com -e SUPERUSER_PASSWORD=test123 ./manage.py createsuperuser
```
=> Allow setting up superuser with command parameters
