- hc/settings.py
Set a relative path for the local_settings.py to work in Python 3.4
> Python 3.4 local_settings

- requirements.txt
Add django-appconf to requirements
> Missing django-appconf requirement

- hc/api/management/commands/sendalerts.py
- hc/api/models.py
- requirements.txt
this will allow alerts to be sent in parallel
i think you're going to have to have something like this in place to scale better
the __init__ files are necessary for the management commands to be picked up as modules
> sendalerts concurrently

- hc/front/views.py
- when u compare `channel.user` to `request.user`, it will issue a 2nd SQL query to fetch the related user object, do id comparison instead to save the extra query
- does the `channels.checks = new_checks` line really work as intended previous? I need to add unit test to verify
- grabbing `channel.checks.all()` and then grabbing only the `code` is not efficient compared to a `values_list`
> fix and optimize checks channel view

- hc/accounts/backends.py
- hc/api/management/commands/sendalerts.py
- hc/front/tests/test_add_channel.py
- hc/front/tests/test_add_check.py
- hc/front/tests/test_channel_checks.py
- hc/front/tests/test_log.py
- hc/front/tests/test_my_checks.py
- hc/front/tests/test_remove_channel.py
- hc/front/tests/test_remove_check.py
- hc/front/tests/test_update_channel.py
- hc/front/tests/test_update_name.py
- hc/front/tests/test_update_timeout.py
- hc/front/tests/test_verify_email.py
- hc/front/views.py
- hc/payments/tests/test_billing.py
- hc/payments/tests/test_cancel_plan.py
- hc/payments/tests/test_create_plan.py
- hc/payments/tests/test_get_client_token.py
- hc/payments/tests/test_invoice.py
- hc/payments/tests/test_pricing.py
- templates/front/channel_checks.html
- templates/front/channels.html
- templates/front/my_checks.html
- templates/payments/pricing.html
later, the test case should be refactored out into a custom base test case that creates the `alice` user so that there's not so much redundant code
> fix tests and optimize authentication and fix some unclosed markup

- .travis.yml
- hc/accounts/tests/test_check_token.py
- hc/api/management/commands/ensuretriggers.py
- hc/api/tests/test_email_webhook.py
- hc/api/tests/test_ensuretriggers.py
- hc/api/tests/test_notify.py
- hc/api/tests/test_ping.py
- hc/api/tests/test_sendalerts.py
- hc/api/tests/test_status.py
- hc/front/tests/test_add_channel.py
- hc/front/tests/test_add_check.py
- hc/front/tests/test_basics.py
- hc/front/tests/test_channel_checks.py
- hc/front/tests/test_log.py
- hc/front/tests/test_my_checks.py
- hc/front/tests/test_remove_channel.py
- hc/front/tests/test_remove_check.py
- hc/front/tests/test_update_channel.py
- hc/front/tests/test_update_name.py
- hc/front/tests/test_update_timeout.py
- hc/front/tests/test_verify_email.py
- hc/payments/tests/test_billing.py
- hc/payments/tests/test_cancel_plan.py
- hc/payments/tests/test_create_plan.py
- hc/payments/tests/test_get_client_token.py
- hc/payments/tests/test_invoice.py
- hc/payments/tests/test_pricing.py
- hc/test.py
should not be duplicating so much code for the base test case setup
> use basetestcase for most test cases that require predefined user

- hc/api/models.py
- hc/api/tests/test_list_checks.py
I would like to be able to additionally fetch the status of a check through the rest api.
> exposes the status field over the rest api

- requirements.txt
> updates django to 1.10.1

- hc/api/views.py
- templates/front/docs_api.html
It only checks for name uniqueness.
for #82
> adds a unique parameter to the check creation API

- hc/api/tests/test_list_checks.py
- hc/api/views.py
- templates/front/docs_api.html
- templates/front/snippets/list_checks_request_filtered.html
- templates/front/snippets/list_checks_request_filtered.txt
- templates/front/snippets/list_checks_response_filtered.html
- templates/front/snippets/list_checks_response_filtered.txt
I thought filtering checks by tags through API would be nice to have.
I am not a python guru or django guru, so feedbacks to improve are welcome.
Update: Documentation is going to be updated in this PR as well.
> Tags querystring param to filter checks by tags

- templates/integrations/add_pagertree.html
> Fix typo: "appropriate"

- hc/settings.py
Makes it possible to define the path of the sqlite file and adds the environment variables "USE_PAYMENTS" and "REGISTRATION_OPEN"
> Improve environment variables support

- README.md
With a fresh install of Ubuntu 18.10 I had to install both python3-venv and python-pip . I also had issues with wheel, I had to delete it and then re-add the requirements for some reason?
> Updated Build instructions

- README.md
Thanks for your help on https://github.com/healthchecks/healthchecks/issues/285 ! PR so you don't have to repeat yourself to other confused users :)
> Adjusted Pushover notes for clarity on behaviour

- hc/api/tests/test_update_check.py
- hc/api/views.py
- templates/front/docs_api.html
> set/update the checks description through the API

- README.md
Updated default port in README.md to 8000
> Updated default port in readme

- hc/api/models.py
- hc/api/tests/test_get_check.py
- hc/api/tests/test_update_check.py
- hc/api/urls.py
- hc/api/views.py
- templates/docs/api.html
- templates/docs/api.md
This PR address #337, and allows for the API to return information on a single check based on its UUID.
> Api single check

- CHANGELOG.md
- hc/api/tests/test_get_check.py
- hc/api/urls.py
- hc/api/views.py
- templates/docs/api.md
This new PR replaces #372 and addresses the concerns raised in recent comments on #370.
> Implementing new changes discussed to resolve #370

- hc/api/models.py
- hc/api/tests/test_get_flips.py
- hc/api/urls.py
- hc/api/views.py
- templates/docs/api.md
This PR contains changes to address #349 in light of discussion there.
> Return single history

- hc/accounts/tests/test_signup.py
Resolves #408 by fixing the test_signup logic bug introduced in 8c13457.
> Fix logic bug in test_signup (#408)

- hc/api/management/commands/smtpd.py
- hc/api/tests/test_smtpd.py
This PR changes the behaviour of mail subject processing to treat failures before success.
Closes #533
> feat: treat failure before success

- README.md
Fixing the URL path to Cron dialog screenshot in static/img with 2x zoom
> Closing #645

- hc/api/tests/test_create_check.py
- hc/api/tests/test_update_check.py
- hc/api/views.py
- templates/docs/api.md
> Expose subject and subject_fail via API

- hc/api/tests/test_notify_webhook.py
- hc/api/transports.py
Adds support for sending ping body contents with webhooks.
Only allowed in the 'body' template of the webhook configuration.
Currently only e-mail transport supports including the ping body in the notification.
Implementing this for webhooks seemed like the right place for maximum flexibility.
Example uses:
* Use Amazon API Gateway to receive and stash a copy of failure log on your own S3 account. (Inspired by discussion at https://github.com/bdd/runitor/issues/60)
* Use IFTTT, Zapier, n8n, etc. to receive the full context of a check status change.
> Webhooks support for $BODY placeholder

- README.md
for pycurl when setting up a development environment.
> updated README.md to include MacOS specific instructions

- hc/api/tests/test_notify_mattermost.py
- hc/api/tests/test_notify_slack.py
- hc/api/transports.py
- templates/integrations/slack_message.json
PR for #784, very similar to #735 and #783
Now includes the BODY in the alert message
> Amended Mattermost class to include the BODY in the message

- hc/api/tests/test_notify_telegram.py
- hc/api/transports.py
- templates/integrations/telegram_message.html
As per title, inspired by #735
> Add body to Telegram notifications

- README.md
> Add link to CI badge in README

- README.md
- templates/docs/self_hosted_configuration.html-fragment
- templates/docs/self_hosted_configuration.md
Replace `healtchecks` with `healthchecks`
> Replace healtchecks with healthchecks

- hc/front/views.py
Refs https://github.com/typeddjango/django-stubs/issues/1755
> Try fixing mypy issues.

- templates/front/filtering_rules_modal.html
> Fix typo in email filtering

- hc/front/forms.py
- hc/front/templatetags/hc_extras.py
- hc/front/tests/test_log.py
- hc/front/tests/test_log_events.py
- hc/front/urls.py
- hc/front/views.py
- static/css/log.css
- static/css/variables.css
- static/js/details.js
- static/js/log.js
- templates/front/log.html
> Add auto-refresh functionality to log page

- templates/docs/go.md
- templates/docs/resources.md
Battle-tested in prod for etke.cc services :)
> docs: add gitlab.com/etke.cc/go/healthchecks example to go page

- static/js/details.js
- static/js/log.js
> format dates in logs to include year unless they are from current year

- templates/docs/self_hosted.html-fragment
- templates/docs/self_hosted.md
Fix django version in self hosted documentation From 4 to 5
> Fix django version in self hosted documentation
